---
# tasks file for mysql
- name: Create MySQL database and user
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Create MySQL database
      mysql_db:
        name: "{{ wp_mysql_db }}"
        state: present

    - name: Create MySQL user
      mysql_user:
        name: "{{ wp_mysql_user }}"
        password: "{{ wp_mysql_password }}"
        priv: "*.*:ALL"
